spring:
  data:
    mongodb:
      database: mongo_udemy_rest_aws
      uri: mongodb://localhost:27018/mongo_udemy_rest_aws?retryWrites=true&w=majority
mongock:
  change-logs-scan-package: br.com.hibejix.restaws.pessoa.config
