info:
  app:
    name: '@project.name@'
    description: '@project.description@'
  build:
    groupId: '@project.groupId@'
    artifact: '@project.artifactId@'
    version: '@project.version@'
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}

spring:
  data:
    mongodb:
      database: mongo_udemy_rest_aws
      uri: mongodb://localhost:27018/mongo_udemy_rest_aws?retryWrites=true&w=majority
mongock:
  change-logs-scan-package: br.com.hibejix.restaws.pessoa.config

jwt:
  secret: SequenciaDeCaracteresParaAssinatToken
  expiration: 60000